# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z54AG2NsvHo9uKxtm8HdNPw4pIpdTWko
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
from statsmodels.formula.api import ols

from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

df = pd.read_excel('Cardheko_RealtimeData.xlsx')
print(df.head())
print(df.shape)
df['selling_price'].describe()
sns.distplot(df['selling_price'])

# Create dummies
df['seller_type_Dealer'] = np.where(df['seller_type'] == 'Dealer', 1, 0)
df['transmission_Auto'] = np.where(df['transmission_type'] == 'Automatic', 1, 0)
df['fuel_Diesel'] = np.where(df['fuel_type'] == 'Diesel', 1, 0)
df['fuel_CNG'] = np.where(df['fuel_type'] == 'CNG', 1, 0)
df['fuel_LPG'] = np.where(df['fuel_type'] == 'LPG', 1, 0)

print(df[['seller_type', 'seller_type_Dealer', 'transmission_type', 'transmission_Auto']].head())

"""Model 1 = Simple Linear regression|
Y = Selling Price |
X = Vehicle Age (Year)
"""

model1 = ols('selling_price ~ vehicle_age', data=df).fit()
print(model1.summary())

y_pred1 = model1.predict(df[['vehicle_age']])
rmse1 = np.sqrt(mean_squared_error(df['selling_price'], y_pred1))
print("RMSE for Model 1:", rmse1)

"""Model 2 = Multiple regression|
Y = Selling Price |
X = Vehicle Age (Year) , Mileage
"""

model2 = ols('selling_price ~ vehicle_age + mileage', data=df).fit()
print(model2.summary())

y_pred2 = model2.predict(df[['vehicle_age', 'mileage']])
rmse2 = np.sqrt(mean_squared_error(df['selling_price'], y_pred2))
print("RMSE for Model 2:", rmse2)

"""Model 3 = Multiple regression| Y = Selling Price | X = Vehicle Age (Year), Mileage, seller_d"""

model3 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer', data=df).fit()
print(model3.summary())

y_pred3 = model3.predict(df[['vehicle_age', 'mileage', 'seller_type_Dealer']])
rmse3 = np.sqrt(mean_squared_error(df['selling_price'], y_pred3))
print("RMSE for Model 3:", rmse3)

"""Model 4 = Multiple regression| Y = Selling Price | X = Vehicle Age (Year), Mileage, seller_d, Transmisssion_auto"""

model4 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer + transmission_Auto', data=df).fit()
print(model4.summary())

y_pred4 = model4.predict(df[['vehicle_age', 'mileage', 'seller_type_Dealer', 'transmission_Auto']])
rmse4 = np.sqrt(mean_squared_error(df['selling_price'], y_pred4))
print("RMSE for Model 4:", rmse4)

"""Model 5 = Multiple regression| Y = Selling Price | X = Vehicle Age (Year), Mileage, seller_d, Transmisssion_auto, Fuel dummies"""

model5 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer + transmission_Auto + fuel_Diesel + fuel_CNG + fuel_LPG', data=df).fit()
print(model5.summary())

y_pred5 = model5.predict(df[['vehicle_age', 'mileage', 'seller_type_Dealer', 'transmission_Auto', 'fuel_Diesel', 'fuel_CNG', 'fuel_LPG']])
rmse5 = np.sqrt(mean_squared_error(df['selling_price'], y_pred5))
print("RMSE for Model 5:", rmse5)

"""Model 6 = Multiple regression| Y = Selling Price | X = Vehicle Age (Year), Mileage, seller_d, Transmisssion_auto, Fuel dummies, engine + max power"""

model6 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer + transmission_Auto + fuel_Diesel + fuel_CNG + fuel_LPG + engine + max_power', data=df).fit()
print(model6.summary())

y_pred6 = model6.predict(df[['vehicle_age', 'mileage', 'seller_type_Dealer', 'transmission_Auto', 'fuel_Diesel', 'fuel_CNG', 'fuel_LPG', 'engine', 'max_power']])
rmse6 = np.sqrt(mean_squared_error(df['selling_price'], y_pred6))
print("RMSE for Model 6:", rmse6)

"""Model 7 = Improved version with outlier treatment"""

df7 = df.copy()

Q1 = df7['selling_price'].quantile(0.25)
Q3 = df7['selling_price'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df7['selling_price'] = np.where(df7['selling_price'] > upper, upper,
                        np.where(df7['selling_price'] < lower, lower, df7['selling_price']))

model7 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer + transmission_Auto + fuel_Diesel + fuel_CNG + fuel_LPG + engine + max_power', data=df7).fit()
print(model7.summary())

y_pred7 = model7.predict(df7[['vehicle_age', 'mileage', 'seller_type_Dealer', 'transmission_Auto', 'fuel_Diesel', 'fuel_CNG', 'fuel_LPG', 'engine', 'max_power']])
rmse7 = np.sqrt(mean_squared_error(df7['selling_price'], y_pred7))
print("RMSE for Model 7 (after outlier treatment):", rmse7)

"""Model 8 = Replacing outliers with means"""

# Model 8: Replace outliers with MEAN (for comparison only)
df8 = df.copy()

Q1 = df8['selling_price'].quantile(0.25)
Q3 = df8['selling_price'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Replace with MEAN instead of bounds
mean_price = df8['selling_price'].mean()
df8['selling_price'] = np.where(df8['selling_price'] > upper, mean_price,
                        np.where(df8['selling_price'] < lower, mean_price, df8['selling_price']))

model8 = ols('selling_price ~ vehicle_age + mileage + seller_type_Dealer + transmission_Auto + fuel_Diesel + fuel_CNG + fuel_LPG + engine + max_power', data=df8).fit()
print(model8.summary())

y_pred8 = model8.predict(df8[['vehicle_age','mileage','seller_type_Dealer','transmission_Auto','fuel_Diesel','fuel_CNG','fuel_LPG','engine','max_power']])
rmse8 = np.sqrt(mean_squared_error(df8['selling_price'], y_pred8))
print("RMSE for Model 8 (outliers replaced with MEAN):", rmse8)

"""### Model Interpretations

#### **Model 1: Simple Linear Regression**
*   **R-squared:** 0.058. This means that approximately 5.8% of the variability in selling price can be explained solely by the vehicle's age.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: For every additional year a vehicle ages, the selling price is estimated to decrease by approximately ₹71,760.

#### **Model 2: Multiple Regression (vehicle_age, mileage)**
*   **R-squared:** 0.203. This means that approximately 20.3% of the variability in selling price can be explained by vehicle age and mileage.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding mileage constant, for every additional year a vehicle ages, the selling price is estimated to decrease by approximately ₹101,800.
    *   `mileage`: Holding vehicle age constant, for every unit increase in mileage, the selling price is estimated to decrease by approximately ₹84,430.

#### **Model 3: Multiple Regression (vehicle_age, mileage, seller_type_Dealer)**
*   **R-squared:** 0.219. This indicates that about 21.9% of the variability in selling price is explained by vehicle age, mileage, and whether the seller is a dealer.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`, `seller_type_Dealer`
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹102,800.
    *   `mileage`: Holding other variables constant, each unit increase in mileage decreases the selling price by approximately ₹82,490.
    *   `seller_type_Dealer`: On average, if the seller is a dealer (compared to an individual), the selling price is estimated to be approximately ₹228,600 higher, holding other variables constant.

#### **Model 4: Multiple Regression (vehicle_age, mileage, seller_type_Dealer, transmission_Auto)**
*   **R-squared:** 0.321. This model explains about 32.1% of the variability in selling price, a notable improvement over previous models.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`, `seller_type_Dealer`, `transmission_Auto`
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹85,470.
    *   `mileage`: Holding other variables constant, each unit increase in mileage decreases the selling price by approximately ₹59,420.
    *   `seller_type_Dealer`: On average, a dealer-sold vehicle has an estimated selling price approximately ₹109,500 higher than an individually-sold vehicle, holding other factors constant.
    *   `transmission_Auto`: On average, an automatic transmission vehicle has an estimated selling price approximately ₹763,100 higher than a manual transmission vehicle, holding other factors constant.

#### **Model 5: Multiple Regression (vehicle_age, mileage, seller_type_Dealer, transmission_Auto, fuel_Diesel, fuel_CNG, fuel_LPG)**
*   **R-squared:** 0.392. This model explains about 39.2% of the variability in selling price.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`, `seller_type_Dealer`, `transmission_Auto`, `fuel_Diesel`, `fuel_CNG` (fuel_LPG is not significant with p=0.100).
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹90,040.
    *   `mileage`: Holding other variables constant, each unit increase in mileage decreases the selling price by approximately ₹68,880.
    *   `seller_type_Dealer`: Dealer-sold vehicles are estimated to be approximately ₹95,010 more expensive.
    *   `transmission_Auto`: Automatic transmission vehicles are estimated to be approximately ₹727,600 more expensive.
    *   `fuel_Diesel`: Diesel vehicles are estimated to be approximately ₹484,600 more expensive than petrol vehicles (the baseline).
    *   `fuel_CNG`: CNG vehicles are estimated to be approximately ₹399,500 more expensive than petrol vehicles.

#### **Model 6: Multiple Regression (vehicle_age, mileage, seller_type_Dealer, transmission_Auto, fuel_Diesel, fuel_CNG, fuel_LPG, engine, max_power)**
*   **R-squared:** 0.629. This model explains a substantial 62.9% of the variability in selling price, indicating a much better fit.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`, `transmission_Auto`, `fuel_CNG`, `fuel_LPG`, `engine`, `max_power` (Note: `seller_type_Dealer` (p=0.292) and `fuel_Diesel` (p=0.179) are not statistically significant in this model).
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹68,850.
    *   `mileage`: Holding other variables constant, each unit increase in mileage *increases* the selling price by approximately ₹15,130. (This counter-intuitive result often signals potential issues like multicollinearity, which is supported by the high condition number).
    *   `transmission_Auto`: Automatic transmission vehicles are estimated to be approximately ₹122,200 more expensive.
    *   `fuel_CNG`: CNG vehicles are estimated to be approximately ₹109,800 more expensive than petrol vehicles.
    *   `fuel_LPG`: LPG vehicles are estimated to be approximately ₹476,900 more expensive than petrol vehicles.
    *   `engine`: For every 1 unit increase in engine displacement, the selling price is estimated to increase by approximately ₹119.
    *   `max_power`: For every 1 unit increase in max power, the selling price is estimated to increase by approximately ₹14,740.
    *   **Note:** The condition number (2.98e+04) is large, suggesting potential multicollinearity issues, which can make individual coefficient interpretations less reliable.

#### **Model 7: Improved Version with Outlier Treatment (Capping)**
*   **R-squared:** 0.807. This model explains a very high 80.7% of the variability in selling price, demonstrating a significant improvement after outlier treatment.
*   **Statistically Significant Variables (p < 0.05):** All variables in the model are statistically significant: `vehicle_age`, `mileage`, `seller_type_Dealer`, `transmission_Auto`, `fuel_Diesel`, `fuel_CNG`, `fuel_LPG`, `engine`, `max_power`.
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹54,940.
    *   `mileage`: Holding other variables constant, each unit increase in mileage decreases the selling price by approximately ₹16,080. (This coefficient now has a more intuitive negative sign compared to Model 6, likely due to the outlier capping).
    *   `seller_type_Dealer`: On average, if the seller is a dealer, the selling price is estimated to be approximately ₹35,290 higher.
    *   `transmission_Auto`: On average, an automatic transmission vehicle has an estimated selling price approximately ₹131,000 higher.
    *   `fuel_Diesel`: Diesel vehicles are estimated to be approximately ₹182,900 more expensive than petrol vehicles.
    *   `fuel_CNG`: CNG vehicles are estimated to be approximately ₹106,000 more expensive than petrol vehicles.
    *   `fuel_LPG`: LPG vehicles are estimated to be approximately ₹104,700 more expensive than petrol vehicles.
    *   `engine`: For every 1 unit increase in engine displacement, the selling price is estimated to increase by approximately ₹37.
    *   `max_power`: For every 1 unit increase in max power, the selling price is estimated to increase by approximately ₹4,061.
    *   **Note:** While the R-squared significantly improved and coefficients are generally more intuitive, the condition number is still large (2.98e+04), indicating that some multicollinearity might still be present, although its impact on coefficient signs has improved for `mileage`.

#### **Model 8: Replacing Outliers with Mean**
*   **R-squared:** 0.590. This model explains about 59.0% of the variability in selling price.
*   **Statistically Significant Variables (p < 0.05):** `vehicle_age`, `mileage`, `seller_type_Dealer`, `transmission_Auto`, `fuel_Diesel`, `fuel_CNG`, `engine`, `max_power` (Note: `fuel_LPG` is not significant with p=0.734).
*   **Key Coefficient Interpretation:**
    *   `vehicle_age`: Holding other variables constant, each additional year of vehicle age decreases the selling price by approximately ₹46,560.
    *   `mileage`: Holding other variables constant, each unit increase in mileage decreases the selling price by approximately ₹15,480.
    *   `seller_type_Dealer`: On average, a dealer-sold vehicle has an estimated selling price approximately ₹33,340 higher than an individually-sold vehicle.
    *   `transmission_Auto`: On average, an automatic transmission vehicle has an estimated selling price approximately ₹61,230 higher than a manual transmission vehicle.
    *   `fuel_Diesel`: Diesel vehicles are estimated to be approximately ₹167,000 more expensive than petrol vehicles.
    *   `fuel_CNG`: CNG vehicles are estimated to be approximately ₹47,190 more expensive than petrol vehicles.
    *   `engine`: For every 1 unit increase in engine displacement, the selling price is estimated to increase by approximately ₹23.
    *   `max_power`: For every 1 unit increase in max power, the selling price is estimated to increase by approximately ₹1,429.
    *   **Note:** The condition number (2.98e+04) is large, suggesting potential multicollinearity issues.

### Model Comparison

Let's compare the R-squared and RMSE for all eight models:

| Model | R-squared | RMSE          |
|-------|-----------|---------------|
| Model 1 | 0.058     | 867,556.48    |
| Model 2 | 0.203     | 798,022.05    |
| Model 3 | 0.219     | 790,319.02    |
| Model 4 | 0.321     | 736,528.54    |
| Model 5 | 0.392     | 697,110.46    |
| Model 6 | 0.629     | 544,803.78    |
| Model 7 | 0.807     | 163,536.80    |
| Model 8 | 0.590     | 173,951.69    |

### Best Model

**Model 7** has the **lowest RMSE (163,536.80)** and the **highest R-squared (0.807)**.

### Why Model 7 is the Best Overall

Model 7 is considered the best model overall for the following reasons:

1.  **Significantly Lower RMSE:** The Root Mean Squared Error (RMSE) is a measure of the average magnitude of the errors. A lower RMSE indicates that the model's predictions are closer to the actual values. Model 7's RMSE is substantially lower than all other models, meaning it makes more accurate predictions of the selling price.

2.  **Highest R-squared:** The R-squared value represents the proportion of the variance in the dependent variable (selling price) that can be predicted from the independent variables. Model 7's R-squared of 0.807 indicates that approximately 80.7% of the variability in selling price can be explained by the predictors in this model, which is a significant improvement over other models.

3.  **Effective Outlier Treatment (Capping):** Model 7 uses a capping method to treat outliers in the `selling_price` variable by replacing values outside the IQR range with the upper and lower bounds. This approach is more robust than replacing with the mean (as seen in Model 8) because it preserves the order and relative magnitude of the values within the defined bounds, leading to a more consistent data distribution and better model performance. Outliers can heavily skew regression coefficients and inflate error metrics, so handling them appropriately leads to a more robust and accurate model.

4.  **All Variables Statistically Significant:** In Model 7, all included independent variables (`vehicle_age`, `mileage`, `seller_type_Dealer`, `transmission_Auto`, `fuel_Diesel`, `fuel_CNG`, `fuel_LPG`, `engine`, `max_power`) are statistically significant (p < 0.05). This suggests that each variable contributes meaningfully to explaining the variation in selling price within this refined model.

In summary, Model 7, by effectively addressing outliers through capping and incorporating a comprehensive set of relevant predictors, provides the most accurate and reliable predictions for car selling prices among the models tested.

### Conclusion and Recommendations

*   **Best Model for Prediction:** Model 7, which incorporates outlier treatment, is highly recommended for used car price prediction. It demonstrates superior accuracy with the lowest Root Mean Squared Error (RMSE) and explains the highest proportion of variance in selling price (R-squared of 0.807).
*   **Key Factors Affecting Price:** According to Model 7, the most influential factors driving used car prices are **vehicle age** (negative impact), **mileage** (negative impact), **transmission type** (automatic transmissions command significantly higher prices), **fuel type** (diesel, CNG, and LPG variants are more expensive than petrol), and **engine specifications** (higher engine displacement and maximum power generally increase price).
*   **Recommendations:** The significant improvement observed in Model 7 underscores the importance of **outlier treatment** in financial and economic modeling. Addressing extreme values in the dataset led to a more robust and interpretable model, providing more reliable predictions for used car selling prices. Further analysis could explore interaction effects between variables or the impact of brand and model-specific characteristics.
"""

#We did not replace outliers with the mean because the mean itself
#is heavily influenced by the extreme values in a right-skewed distribution.
# Instead, we used IQR capping, which is more robust and resulted in
# the lowest RMSE (Model 7).